name: pylearn_v1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  flutter_riverpod: ^2.5.1
  image_picker: ^1.1.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  youtube_player_flutter: ^9.0.0
  cached_network_image: ^3.3.1
  share_plus: ^9.0.0
  firebase_database: ^11.0.3
  url_launcher: ^6.2.6
  flutter_launcher_icons: ^0.13.1  
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  random_string: ^2.3.1
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.3
  flutter_inappwebview: ^6.0.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/logo.svg
    - assets/icons/splash.svg
    - assets/icons/copyright.svg

